name: "Build Rootfs"
description: "Export the given Docker or Containerfile Rootfs and release it"
inputs:
  flavor:
    description: "Flavor of the image to use in tag"
    required: false
    default: "latest"
outputs:
  release_tag:
    description: "Release Tag"
    value: ${{ steps.release_tag.outputs.new_tag }}
runs:
  using: composite
  steps:
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@master
      id: release_tag
      env:
        DRY_RUN: ${{ github.ref != 'refs/heads/main' }}
        REPO_OWNER: ${{ env.REGISTRY_USER }}
    - name: Release Rootfs
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.release_tag.outputs.new_tag }}
        files: rootfs.tar.gz
    - name: Push
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: docker/build-push-action@v4
      with:
        context: .
        load: false
        push: true
        tags: ${{ env.REGISTRY_IMAGE_TAG }}:${{ steps.release_tag.outputs.new_tag }}